### ISSUE TITLE
Issue regarding arrow realization/abstraction

### ISSUE THREAD

**Issue by anIceyGirl** [anIceyGirl/PrimitiveArmory#1]
Currently there's an issue regarding the spawning of arrows in arena mode. When you enter arena mode with multiple arrows spawned in, all but one of the arrows disappears. Along with that, there appears to be an issue with realization and abstraction, as some peeps on the [RW discord explained.](https://discordapp.com/channels/291184728944410624/431534164932689921/783983711136776203)

The following logs consist of me going into arena mode, spawning a bow along with a dozen arrows, and then firing the arrows into the walls of the arena, before Alt+F4-ing back to desktop.

[exceptionLog.txt](https://github.com/anIceyGirl/PrimitiveArmory/files/5636448/exceptionLog.txt)
[consoleLog.txt](https://github.com/anIceyGirl/PrimitiveArmory/files/5636449/consoleLog.txt)

**Comment by FyreByrns** [comment]
I never like saving objects via the vanilla system in mods, I prefer a mod-specific save file.

**Comment by anIceyGirl** [comment]
I was able to implement a fix thanks to some help from Slime_Cubed in the discord server. Turns out this is a sandbox mode specific issue, but I was able to get around it by hooking into SandboxGameSession.SpawnEntity. [Link](https://github.com/anIceyGirl/PrimitiveArmory/blob/4a86f8f63ec684e9642853f482ac8405b190d686/Main.cs#L203)
